# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = false
  block_timestamp = 1_680_220_800                           # March 31, 2023 at 00:00 GMT
  bytecode_hash = "none"
  evm_version = "paris"                                     # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  solc = "0.8.25"
  src = "src"
  build_info = true
  extra_output = ["storageLayout"]
  test = "test/unit"
  libs = ["lib"]
  fs_permissions = [{ access = "read-write", path = "./" }]
  ffi = true
  ast = true

[profile.full_test]
  test = "test"
  build_info = true
  extra_output = ["storageLayout"]
  fuzz = { runs = 10_000 }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  mainnet = "${MAINNET_RPC_URL}"
  sepolia = "${SEPOLIA_RPC_URL}"
